version: '3'

# Networking
networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge

# Storage Volumes
volumes:
  caddy_config:
  caddy_data:
  grafana_data:
  prometheus_data:
  rabbitmq_mnesia:
  timescaledb_data:
  vault_file:
  vault_logs:

# Docker Services
services:
  # Fluent-Bit (Logging)
  fluent-bit:
    build:
      context: './docker/fluent-bit'
    restart: unless-stopped
    ports:
      - '2020:2020'
      - '24224:24224'
      - '24224:24224/udp'
    networks:
      - backend

  # Prometheus (Time Series DB)
  prometheus:
    build:
      context: './docker/prometheus'
    restart: unless-stopped
    ports:
      - '9090:9090'
      - '9092:9092'
    volumes:
      - prometheus_data:/prometheus
    networks:
      - frontend
      - backend
    depends_on:
      - fluent-bit
    logging:
      driver: 'fluentd'
      options:
        tag: prometheus

  # Grafana (Dashboards)
  grafana:
    build:
      context: './docker/grafana'
    restart: unless-stopped
    ports:
      - '3001:3000'
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - frontend
      - backend
    depends_on:
      - fluent-bit
      - prometheus
    logging:
      driver: 'fluentd'
      options:
        tag: grafana

  # Caddy (Proxy)
  caddy:
    build:
      context: './docker/caddy'
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./docker/caddy/config/Caddyfile:/etc/caddy/Caddyfile
      - ./build:/srv
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - frontend
      - backend
    depends_on:
      - fluent-bit
    logging:
      driver: 'fluentd'
      options:
        tag: caddy

  # Vault
  vault:
    build:
      context: './docker/vault'
    restart: unless-stopped
    ports:
      - '${VAULT_PORT}:${VAULT_PORT}'
    volumes:
      - vault_file:/vault/file
      - vault_logs:/vault/logs
    networks:
      - frontend
      - backend
    depends_on:
      - fluent-bit
    logging:
      driver: 'fluentd'
      options:
        tag: vault

  # Node (JS Engine)
  node:
    build:
      context: .
    restart: unless-stopped
    ports:
      - '3000:3000'
    networks:
      - backend
    depends_on:
      - fluent-bit
    logging:
      driver: 'fluentd'
      options:
        tag: node

  # RabbitMQ (Message Broker)
  rabbitmq:
    build:
      context: './docker/rabbitmq'
    restart: unless-stopped
    volumes:
      - rabbitmq_mnesia:/var/lib/rabbitmq
    ports:
      - '15672:15672'
    networks:
      - backend
    depends_on:
      - fluent-bit
    logging:
      driver: 'fluentd'
      options:
        tag: rabbitmq

  # TimescaleDB (Time Series DB)
  timescaledb:
    build:
      context: './docker/timescaledb'
    restart: unless-stopped
    volumes:
      - timescaledb_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - backend
    logging:
      driver: 'fluentd'
      options:
        tag: timescaledb
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres

  # Promscale (Logs Connector)
  promscale:
    build:
      context: './docker/promscale'
    ports:
      - 9201:9201
    networks:
      - backend
    restart: unless-stopped
    depends_on:
      - timescaledb
      - prometheus
    environment:
      PROMSCALE_DB_CONNECT_RETRIES: 10
      PROMSCALE_WEB_TELEMETRY_PATH: /metrics-text
      PROMSCALE_DB_URI: postgres://postgres:password@timescaledb:5432/postgres?sslmode=allow
