version: '3'

# Networking
networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge

# Storage Volumes
volumes:
  # Caddy
  caddy_data:
  caddy_config:
  # Node
  node_app:

# Docker Services
services:
  # Caddy Proxy
  caddy:
    build:
      context: './docker/caddy'
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./docker/caddy/config/Caddyfile:/etc/caddy/Caddyfile
      - ./build:/srv
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - frontend
      - backend
  # Node JS Engine
  node:
    build:
      context: .
    restart: unless-stopped
    volumes:
      - node_app:/usr/src/app
    networks:
      - backend
