version: '3'

# Networking
networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge

# Storage Volumes
volumes:
  caddy_config:
  caddy_data:
  grafana_data:
  prometheus_data:
  rabbitmq_mnesia:
  timescaledb_data:
  vault_file:
  vault_logs:

# Docker Services
services:
  # Prometheus (Time Series DB)
  prometheus:
    build:
      context: './docker/prometheus'
    restart: unless-stopped
    ports:
      - '9090:9090'
      - '9092:9092'
    volumes:
      - prometheus_data:/prometheus
    networks:
      - frontend
      - backend

  # Grafana (Dashboards)
  grafana:
    build:
      context: './docker/grafana'
    restart: unless-stopped
    ports:
      - '3001:3000'
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - frontend
      - backend
    depends_on:
      - prometheus

  # Caddy (Proxy)
  caddy:
    build:
      context: './docker/caddy'
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./docker/caddy/config/Caddyfile:/etc/caddy/Caddyfile
      - ./build:/srv
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - frontend
      - backend

  # Vault
  vault:
    build:
      context: './docker/vault'
    restart: unless-stopped
    ports:
      - '${VAULT_PORT}:${VAULT_PORT}'
    volumes:
      - vault_file:/vault/file
      - vault_logs:/vault/logs
    networks:
      - frontend
      - backend

  # Node (JS Engine)
  node:
    build:
      context: .
    restart: unless-stopped
    ports:
      - '3000:3000'
    networks:
      - backend

  # RabbitMQ (Message Broker)
  rabbitmq:
    build:
      context: './docker/rabbitmq'
    restart: unless-stopped
    volumes:
      - rabbitmq_mnesia:/var/lib/rabbitmq
    ports:
      - '15672:15672'
    networks:
      - backend

  # TimescaleDB (Time Series DB)
  timescaledb:
    build:
      context: './docker/timescaledb'
    restart: unless-stopped
    volumes:
      - timescaledb_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - backend
    environment:
      POSTGRES_USER: '${POSTGRES_USER:-postgres}'
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD:-password}'

  # Promscale (Logs Connector)
  promscale:
    build:
      context: './docker/promscale'
    ports:
      - 9201:9201
      - 9202:9202
    networks:
      - backend
    restart: unless-stopped
    depends_on:
      - timescaledb
      - prometheus
    environment:
      PROMSCALE_DB_CONNECT_RETRIES: 10
      PROMSCALE_WEB_TELEMETRY_PATH: /metrics-text
      PROMSCALE_DB_URI: postgres://postgres:password@timescaledb:5432/postgres?sslmode=allow

  jaeger-collector:
    build:
      context: './docker/jaeger-collector'
    command:
      - '--cassandra.keyspace=jaeger_v1_dc1'
      - '--cassandra.servers=cassandra'
      - '--collector.zipkin.host-port=9411'
      - '--sampling.initial-sampling-probability=.5'
      - '--sampling.target-samples-per-second=.01'
    environment:
      - SAMPLING_CONFIG_TYPE=adaptive
    ports:
      - '14269:14269'
      - '14268:14268'
      - '14250'
      - '9411:9411'
    restart: unless-stopped
    depends_on:
      - cassandra-schema

  jaeger-query:
    build:
      context: './docker/jaeger-query'
    command: ['--cassandra.keyspace=jaeger_v1_dc1', '--cassandra.servers=cassandra']
    ports:
      - '16686:16686'
      - '16687'
    restart: unless-stopped
    depends_on:
      - cassandra-schema

  jaeger-agent:
    build:
      context: './docker/jaeger-agent'
    command: ['--reporter.grpc.host-port=jaeger-collector:14250']
    ports:
      - '5775:5775/udp'
      - '6831:6831/udp'
      - '6832:6832/udp'
      - '5778:5778'
    restart: unless-stopped
    depends_on:
      - jaeger-collector

  cassandra:
    build:
      context: './docker/cassandra'
    ports:
      - '9042:9042'

  cassandra-schema:
    build:
      context: './docker/cassandra-schema'
    depends_on:
      - cassandra
