global:
  scrape_interval: 10s
  evaluation_interval: 10s
scrape_configs:
  - job_name: fluentbit-exporter
    scheme: http
    metrics_path: /metrics
    static_configs:
      - targets: ['docker.for.mac.host.internal:2021']
  - job_name: cadvisor
    scrape_interval: 5s
    static_configs:
      - targets:
          - docker.for.mac.host.internal:8080
remote_write:
  - url: 'http://promscale:9201/write'
remote_read:
  - url: 'http://promscale:9201/read'
    read_recent: true
